### ISSUE TITLE
Peer-to-peer code review for porfolio

### ISSUE THREAD

**Issue by zainsadaqat** [zainsadaqat/portfolio#5]
Hello Guys!

I'd really appreciate it if you point out mistakes in my project and I'll try to fix them as early as possible.

<img src="https://media3.giphy.com/media/pneG7YsDljrFo2nuFR/giphy.gif"/>

**Comment by rotimiazeez** [comment]
Hi @zainsadaqat 👋🏽,
Good code you have here 👍🏽. It's a good one for me 💪🏽. I only think for the mobile screen contact form you can you the position relative and absolute to fit the icon well on the screen 🤷🏽‍♂️ .
That apart it's a good code 🎉 🚀

**Comment by zainsadaqat** [comment]
### Thank you so much for pointing out my mistake and I'll try to fix it ASAP 👍🏻 😃
