### ISSUE TITLE
Semantics

### ISSUE THREAD

**Issue by AlexHamn** [zainsadaqat/portfolio#6]
https://github.com/zainsadaqat/portfolio/blob/4e348f1330b8ee6fac6b4e9cd0b8d8755fd44b34/index.html#L49

You could use as few div tags as possible and instead use the HTML5 semantic tags; this is true in a couple of sections of your code; this is only one example here you could maybe switch the div for a section tag or maybe an article tag.
Cheers 😄

**Comment by zainsadaqat** [comment]
Thank you so much for your valuable suggestions I'll definitely follow this for my future projects 👍🏻 😃
